ToDo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from tasks import views as task_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # regex for paths that start with 'accounts/'
    # include('accounts.urls') includes the paths declared un accounts/urls.py so they can be matched.
    # same for tasks
    url(r'^accounts/', include('accounts.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^$', task_views.task_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()  # for adding static files to urls (style.css)

tags/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tags'

urlpatterns = [
    url(r'^$', views.tag_list, name='list'),
    url(r'^admin/$', views.tag_admin, name='admin'),
    url(r'^(?P<tag_id>[0-9]+)/delete/$', views.tag_delete, name='delete'),
]

tags/models.py
from django.db import models


class Tag(models.Model):
    title = models.CharField(max_length=15)

    def __str__(self):
        return self.title

tags/forms.py
from django import forms
from . import models


# creates a form using django built in app forms and also using already created models
class CreateTag(forms.ModelForm):
    class Meta:
        model = models.Tag
        fields = ['title']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }

tags/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from .models import Tag
from django.http import HttpResponse
from . import forms


def tag_list(request):
    tags = Tag.objects.all()
    return render(request, 'tags/tag_list.html', {'tags': tags})


@login_required(login_url="/accounts/login/")
def tag_delete(request, tag_id):
    tag = Tag.objects.get(id=tag_id)
    tag.delete()
    return redirect('tags:admin')


@login_required(login_url="/accounts/login/")
def tag_admin(request):
    tags = Tag.objects.all()
    if request.method == 'POST':
        form = forms.CreateTag(request.POST)
        if form.is_valid():
            tag = form.save(commit=False)
            if tag.title[0] != '#':
                tag.title = '#'+tag.title
            tag.save()
        return redirect('tasks:list')
    else:
        tags = Tag.objects.all()
        form = forms.CreateTag()
    return render(request, 'tags/tag_admin.html', {'form': form, 'tags': tags})

tags/templates/tags/tag_admin.html
{% extends 'homepage.html' %}

{% block content %}
<br>
<div class="mb-3" style="margin-left: 5em; padding-top 10em; width: 50em;">
    <div class="create-tag">
        <h2>Create a New TAG</h2>
        <form class="site-form" action="{% url 'tags:admin' %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit"  class="btn btn-primary" value="Create">
        </form>
    </div>

    <div class="delete-tag">
        <h2>Delete TAGs</h2>
        <ul>
        {% for tag in tags %}
            <li>
                <a class="text-danger" href="{% url 'tags:delete' tag_id=tag.id %}">{{ tag }}</a>
            </li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

tags/templates/tags/tag_list.html
{% block content %}
<h1> ESTO ES UNA PRUEBA </h1>

{% for tag in tags %}
    {{ tag }}
{% endfor %}
{% endblock %}