ToDo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from tasks import views as task_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # regex for paths that start with 'accounts/'
    # include('accounts.urls') includes the paths declared un accounts/urls.py so they can be matched.
    # same for tasks
    url(r'^accounts/', include('accounts.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^$', task_views.task_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()  # for adding static files to urls (style.css)

tasks/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    url(r'^$', views.task_list, name='list'),
    url(r'^json$', views.task_to_json, name='task_list'),
    url(r'^create/$', views.task_create, name='create'),
    url(r'^(?P<task_id>[0-9]+)/state/$', views.task_change_state, name='change_state'),
    url(r'^(?P<task_id>[0-9]+)/delete/$', views.task_delete, name='delete'),
    url(r'^(?P<task_id>[0-9]+)/update/$', views.task_update, name='update'),
    url(r'^(?P<id>[0-9]+)/filter/$', views.task_filter, name='filter'),
    # (?P<task_id>[0-9]+) format (?P<VARIABLE>REGEX) specifies the regex for that variable and that will be passed to
    # the view fun. For name='detail' is a name given to reference the URL created dynamically (used on tasks_list.html)
    url(r'^(?P<task_id>[0-9]+)/$', views.task_details, name='detail'),
]

tasks/models.py
from django.db import models
from django.contrib.auth.models import User
from tags.models import Tag


# more info on model types on https://docs.djangoproject.com/en/1.11/ref/models/fields
class Task(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)  # automatically populates date when constructed.
    assigned = models.ManyToManyField(User, default=None)
    tags = models.ManyToManyField(Tag, blank=True)
    IN_PROGRESS = 'IN PROGRESS'
    FINISHED = 'FINISHED'
    STATE_CHOICES = (
        (IN_PROGRESS, 'In Progress'),
        (FINISHED, 'Finished'),
    )
    state = models.CharField(
        max_length=12,
        choices=STATE_CHOICES,
        default=IN_PROGRESS,
    )

    # add in tag list

    def __str__(self):
        return self.title

    def snippet(self):
        if len(str(self.body)) > 40:
            return self.body[0:40] + ' (...)'
        else:
            return self.body

tasks/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from .models import Tag


# creates a form using django built in app forms and also using already created models
class CreateTask(forms.ModelForm):
    class Meta:
        model = models.Task
        fields = ['title', 'body', 'tags', 'state', 'assigned']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'tags': forms.CheckboxSelectMultiple(attrs={'class': 'form-control'}),
            'state': forms.Select(attrs={'class': 'form-control'}),
            'assigned': forms.SelectMultiple(attrs={'class': 'form-control'}),
        }

    tags = forms.ModelMultipleChoiceField(
        queryset=Tag.objects.all(),
        widget=forms.CheckboxSelectMultiple
    )

tasks/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.core import serializers as deserialize
from .models import Task
from tags.models import Tag
from django.contrib.auth.models import User
from . import forms
import json
from rest_framework import serializers
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from notifications.models import Notification


class TagSerializer(serializers.ModelSerializer):
    class Meta:
        model = Tag
        fields = '__all__'
        model = Tag


# Necessary classes to serialize nested objects
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        fields = ['username']
        model = User


class TaskSerializer(serializers.ModelSerializer):
    assigned = UserSerializer(read_only=True, many=True)
    tags = TagSerializer(read_only=True, many=True)

    class Meta:
        fields = '__all__'
        model = Task


def task_list(request):
    tasks = Task.objects.prefetch_related('assigned')
    assigned_tasks = []
    for task in tasks:
        for user in task.assigned.all():
            if user.id == request.user.id:
                assigned_tasks.append(task)

    notifications = Notification.objects.prefetch_related('users')
    count = 0
    for notification in notifications:
        for user in notification.users.all():
            if user.id == request.user.id:
                if notification.status == 'UNREAD':
                    count += 1

    return render(request, 'tasks/tasks_list.html', {'tasks': tasks, 'count': count})


def task_filter(request, id):
    tasks = Task.objects.prefetch_related('assigned').order_by('date')
    assigned_tasks = []
    filteredList = []
    for task in tasks:
        for user in task.assigned.all():
            if user.id == request.user.id:
                assigned_tasks.append(task)

    for task in assigned_tasks:
        tags = task.tags.all()
        for tag in tags:
            if int(tag.id) == int(id):
                filteredList.append(task)

    notifications = Notification.objects.prefetch_related('users')
    count = 0
    for notification in notifications:
        for user in notification.users.all():
            if user.id == request.user.id:
                if notification.status == 'UNREAD':
                    count += 1

    return render(request, 'tasks/tasks_list.html', {'tasks': filteredList, 'count': count})


def task_to_json(request):  # json endpoint for all tasks
    if request.method == 'GET':
        tasks = Task.objects.all()
        data = TaskSerializer(tasks, many=True).data
        return HttpResponse(json.dumps(data))  # json.dump converts dictionary to json


def task_details(request, task_id):
    task = Task.objects.get(id=task_id)
    # Render a template and send data to it.
    # Pass the variable task created to the template with {'task': task}
    return render(request, 'tasks/task_detail.html', {'task': task})


@login_required(login_url="/accounts/login/")
def task_change_state(request, task_id):
    task = Task.objects.get(id=task_id)
    if task.state == task.IN_PROGRESS:
        Notification.notify_user(task, "FINISHED")
        task.state = task.FINISHED
    else:
        task.state = task.IN_PROGRESS
        Notification.notify_user(task, "IN PROGRESS")
    task.save()

    return redirect('tasks:list')


@login_required(login_url="/accounts/login/")
def task_delete(request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    Notification.notify_user(task, "DELETED")
    return redirect('tasks:list')


@login_required(login_url="/accounts/login/")
def task_update(request, task_id):
    if request.method == 'POST':
        task = Task.objects.get(id=task_id)
        form = forms.CreateTask(request.POST, instance=task)  # creates a form with data coming from the request
        if form.is_valid():
            obj = form.save(commit=False)
            userIds = request.POST.getlist('assigned')
            obj.assigned.set(userIds)
            tagIds = request.POST.getlist('tags')
            obj.tags.set(tagIds)
            obj.save()
            Notification.notify_user(task, "UPDATED")
            return redirect('tasks:list')
    else:
        task = Task.objects.get(id=task_id)
        form = forms.CreateTask(initial={
            'id': task_id,
            'title': task.title,
            'body': task.body,
            'state': task.state,
            'assigned': task.assigned.all(),
            'tags': task.tags.all(),
        })  # creates a form object from tasks/forms.py
    return render(request, 'tasks/task_update.html', {'form': form, 'task': task})


# login decorator prevents unauthenticated users
@login_required(login_url="/accounts/login/")
def task_create(request):
    if request.method == 'POST':
        form = forms.CreateTask(request.POST)  # creates a form with data coming from the request
        if form.is_valid():
            task = form.save()
            print(request.user.id)
            Notification.notify_user(task, "CREATED")
        return redirect('tasks:list')
    else:
        form = forms.CreateTask()  # creates a form object from tasks/forms.py
    return render(request, 'tasks/task_create.html', {'form': form})

tasks/templates/tasks/task_create.html
{% extends 'homepage.html' %}

{% block content %}
<br>
    <div class="mb-3" style="margin-left: 5em; width: 50em;">
        <h2>Create a New Task</h2>
        <form action="{% url 'tasks:create' %}" method="POST">

                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" class="btn btn-primary" value="Create">
        </form>
    </div>
{% endblock %}

tasks/templates/tasks/task_detail.html
{% extends 'homepage.html' %}

{% block content %}
    <div class="task-detail">
        <div class="article">
            <h2>{{ task.id }} - {{ task.title }}</h2>
            <p>Assigned to:
                {% for user in task.assigned.all %}
                {{ user }},
                {% endfor %}
            </p>
            <p>{{ task.body }}</p>
            <p>Created on {{ task.date }}</p>
            <p>State: {{ task.state }}</p>
        </div>
    </div>
{% endblock %}

tasks/templates/tasks/task_update.html
{% extends 'homepage.html' %}

{% block content %}
<br>
    <div class="mb-3" style="margin-left: 5em; width: 50em;">
        <h2>Update a Task</h2>
        <form class="site-form" action="{% url 'tasks:update' task_id=task.id %}" method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Update">
        </form>
    </div>
{% endblock %}

tasks/templates/tasks/tasks_list.html
{% extends 'homepage.html' %}
{% block content %}
<main class="py-5">
<div class="row">
    <div class="child table-responsive col-md-6">
        <table>
            <thead>
            <tr>
                <th>IN PROGRESS</th>
            </tr>
            </thead>
            <tbody>

            <div class="tasks">
                {% for task in tasks %}
                <tr>
                    <td>
                        {% if task.state == task.IN_PROGRESS %}
                        <div class="task">
                            <!-- 'tasks.detail' matches the name in urls.py
                            where tasks is the namespace. task_id matches the variable-->
                            <h2><a class="text-info" href="{% url 'tasks:detail' task_id=task.id %}">{{ task.title }}</a></h2>
                            <p><i>task ID: {{ task.id }} - Created on {{ task.date }}</i></p>
                            <p>{{ task.snippet }}</p>
                            <p>Assigned to:
                                {% for user in task.assigned.all %}
                                {{ user }},
                                {% endfor %}
                            </p>
                            <p>{{ task.state }}</p>
                            <div>
                                <a class="badge bg-secondary" href="{% url 'tasks:update' task_id=task.id %}">Update</a>
                                <a class="badge bg-secondary" href="{% url 'tasks:change_state' task_id=task.id %}">Finished</a>
                                <a class="badge bg-danger" href="{% url 'tasks:delete' task_id=task.id %}">Delete</a>
                            </div>
                                tags:
                                {% with tags=task.tags.all %}
                                    {% for tag in tags %}
                                        <span class="badge rounded-pill bg-warning text-dark"><a href="{% url 'tasks:filter' id=tag.id %}">{{ tag }}</a></span>
                                    {% endfor %}
                                {% endwith %}
                        </div>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </div>

            </tbody>
        </table>
    </div>
    <div class="child table-responsive col-md-6">
        <table>
            <thead>
            <tr>
                <th scope="col">FINISHED</th>
            </tr>
            </thead>
            <tbody>

            <div class="tasks">
                {% for task in tasks %}
                <tr>
                    <td>
                        {% if task.state == task.FINISHED %}
                        <div class="task">
                            <!-- 'tasks.detail' matches the name in urls.py
                            where tasks is the namespace. task_id matches the variable-->
                            <h2><a href="{% url 'tasks:detail' task_id=task.id %}">{{ task.title }}</a></h2>
                            <p><i>task ID: {{ task.id }} - Created on {{ task.date }}</i></p>
                            <p>{{ task.snippet }}</p>
                            <p>Assigned to:
                                {% for user in task.assigned.all %}
                                {{ user }},
                                {% endfor %}
                            </p>
                            <p>{{ task.state }}</p>
                            <div>
                                <a class="badge bg-secondary" href="{% url 'tasks:update' task_id=task.id %}">Update</a>
                                <a class="badge bg-secondary" href="{% url 'tasks:change_state' task_id=task.id %}">Not finished</a>
                                <a class="badge bg-danger" href="{% url 'tasks:delete' task_id=task.id %}">Delete</a>
                            </div>
                                tags:
                                {% with tags=task.tags.all %}
                                    {% for tag in tags %}
                                        <span class="badge rounded-pill bg-warning text-dark"><a href="{% url 'tasks:filter' id=tag.id %}">{{ tag }}</a></span>
                                    {% endfor %}
                                {% endwith %}

                        </div>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </div>

            </tbody>
        </table>
    </div>
</div>
</main>
{% endblock %}