ToDo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from tasks import views as task_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # regex for paths that start with 'accounts/'
    # include('accounts.urls') includes the paths declared un accounts/urls.py so they can be matched.
    # same for tasks
    url(r'^accounts/', include('accounts.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^$', task_views.task_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()  # for adding static files to urls (style.css)

accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name='signup'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
]

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = 'notifications'

urlpatterns = [
    url(r'^$', views.notification_list, name='list'),
    url(r'^(?P<notification_id>[0-9]+)/delete/$', views.notification_delete, name='delete'),
    url(r'^(?P<notification_id>[0-9]+)/$', views.notification_details, name='detail'),
]

tags/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tags'

urlpatterns = [
    url(r'^$', views.tag_list, name='list'),
    url(r'^admin/$', views.tag_admin, name='admin'),
    url(r'^(?P<tag_id>[0-9]+)/delete/$', views.tag_delete, name='delete'),
]

tasks/urls.py
from django.conf.urls import url
from django.urls import path
from . import views

app_name = 'tasks'

urlpatterns = [
    url(r'^$', views.task_list, name='list'),
    url(r'^json$', views.task_to_json, name='task_list'),
    url(r'^create/$', views.task_create, name='create'),
    url(r'^(?P<task_id>[0-9]+)/state/$', views.task_change_state, name='change_state'),
    url(r'^(?P<task_id>[0-9]+)/delete/$', views.task_delete, name='delete'),
    url(r'^(?P<task_id>[0-9]+)/update/$', views.task_update, name='update'),
    url(r'^(?P<id>[0-9]+)/filter/$', views.task_filter, name='filter'),
    # (?P<task_id>[0-9]+) format (?P<VARIABLE>REGEX) specifies the regex for that variable and that will be passed to
    # the view fun. For name='detail' is a name given to reference the URL created dynamically (used on tasks_list.html)
    url(r'^(?P<task_id>[0-9]+)/$', views.task_details, name='detail'),
]

templates/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ToDo UTN</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <h1>ToDo UTN</h1>
    <hr>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<header>
<nav>
    <ul>
        <li><a class="btn btn-outline-dark" href="{% url 'home' %}">Home</a></li>
        {% if user.is_authenticated %}
        <li>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <button class="btn btn-outline-dark" type="submit">Logout</button>
            </form>
        </li>
        <li>Hi {{ user.username }}!</li>

        {% else %}
        <li><a class="btn btn-outline-dark" href="{% url 'accounts:login' %}">Login</a></li>
        <li><a class="btn btn-outline-dark" href="{% url 'accounts:signup' %}">Signup</a></li>
        {% endif %}
        <li><a class="btn btn-outline-dark" href="{% url 'tags:admin' %}">TAGs</a></li>
        <li><a class="btn btn-outline-primary" href="{% url 'tasks:create' %}">CREATE TASK</a> </li>
        <li><a class="btn btn-outline-dark" href="{% url 'notifications:list' %}">NOTIFICATIONS        </a>
        </li>
        {% if user.is_authenticated %}
         <span class="alert alert-danger">
            {{ count }}
         </span>
        {% endif %}

    </ul>
</nav>
</header>
<body>
    {% block content %}
    {% endblock %}
</body>

<hr>
<footer>Thank you for visiting us!</footer>
</html>