ToDo/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import views
from tasks import views as task_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # regex for paths that start with 'accounts/'
    # include('accounts.urls') includes the paths declared un accounts/urls.py so they can be matched.
    # same for tasks
    url(r'^accounts/', include('accounts.urls')),
    url(r'^tasks/', include('tasks.urls')),
    url(r'^tags/', include('tags.urls')),
    url(r'^notifications/', include('notifications.urls')),
    url(r'^$', task_views.task_list, name="home")
]

urlpatterns += staticfiles_urlpatterns()  # for adding static files to urls (style.css)

notifications/urls.py
from django.conf.urls import url
from . import views

app_name = 'notifications'

urlpatterns = [
    url(r'^$', views.notification_list, name='list'),
    url(r'^(?P<notification_id>[0-9]+)/delete/$', views.notification_delete, name='delete'),
    url(r'^(?P<notification_id>[0-9]+)/$', views.notification_details, name='detail'),
]

notifications/models.py
from django.db import models

# Create your models here.
from django.db.models import CASCADE
from django.contrib.auth.models import User
from tasks.models import Task


class Notification(models.Model):
    title = models.CharField(max_length=50)
    reason = models.CharField(max_length=200)
    reporter = models.ForeignKey(Task, on_delete=CASCADE)
    users = models.ManyToManyField(User)
    UNREAD = 'UNREAD'
    READ = 'READ'
    STATUS_CHOICES = [
        (UNREAD, 'Unread'),
        (READ, 'Read'),
    ]
    status = models.CharField(
        choices=STATUS_CHOICES,
        default=UNREAD,
        max_length=12
    )
    ALERT = 'ALERT'
    IMPORTANT = 'IMPORTANT'
    MUST = 'MUST'
    CRITICAL = 'CRITICAL'
    TYPE_CHOICES = [
        (ALERT, 'This is just an alert'),
        (IMPORTANT, 'This is very important '),
        (MUST, 'This must be done at the end of the day'),
        (CRITICAL, 'This is already delayed'),
    ]
    type = models.CharField(
        choices=TYPE_CHOICES,
        default=ALERT,
        max_length=12
    )

    def __str__(self):
        return self.title

    def snippet(self):
        if len(str(self.reason)) > 20:
            return self.body[0:20] + ' (...)'
        else:
            return self.body

    @staticmethod
    def notify_user(task, reason):

        notification = Notification()
        notification.title = task.title
        notification.reason = reason
        notification.reporter = task
        notification.save()
        for u in task.assigned.all():
            notification.users.add(u)

notifications/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Notification
from tasks.models import Task
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy

# Create your views here.


@login_required(login_url="/accounts/login/")
def notification_list(request):
    notifications = Notification.objects.prefetch_related('users')
    user_notifications = []
    for notification in notifications:
        for user in notification.users.all():
            if user.id == request.user.id:
                user_notifications.append(notification)
    return render(request, 'notifications/notification-list.html', {'notifications': user_notifications})


@login_required(login_url="/accounts/login/")
def notification_details(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    notification.status = 'READ'
    notification.save()
    task = Task.objects.get(notification=notification)
    return render(request, 'notifications/notification-details.html', {'notification': notification, 'task': task})


@login_required(login_url="/accounts/login/")
def notification_delete(request, notification_id):
    notification = Notification.objects.get(id=notification_id)
    notification.delete()
    return redirect('notifications:list')

notifications/templates/notifications/notification-details.html
{% extends 'homepage.html' %}
{% block content %}
<main class="py-5">
    <section class="mb-5">
      <div class="container">
          <h3 class="mb-3">Notification Nr  {{ notification.id }}</h3>
          <div class="bg-light p-4">
              <div class="row">
                      <div class="col-lg-4">
                          <label for=""> Notification Type :</label>
                      </div>
                      <div class="col-lg-4">
                          <label for="">Reason</label>
                      </div>
                      <div class="col-lg-4 my-0">
                          <label for="">Type</label>
                      </div>
                      <div class="col-lg-4">
                            {{ notification.title }}
                      </div>
                      <div class="col-lg-4">
                                {{ notification.reason }}
                      </div>
                      <div class="col-lg-4">
                            {{ notification.type }}
                      </div>
                  <div>
                      <div class="col-lg-4">

                          <label class =""for="">Task</label>
                                  <div class="task-detail">
                                            <div class="article">
                                                <h3>{{ task.id }} - {{ task.title }}</h3>
                                                <p>Assigned to:
                                                    {% for user in task.assigned.all %}
                                                    {{ user }},
                                                    {% endfor %}
                                                </p>
                                                <p>{{ task.body }}</p>
                                                <p>Created on {{ task.date }}</p>
                                                <p>State: {{ task.state }}</p>
                                            </div>
                                  </div>
                      </div>
                 </div>
              </div>
          </div>
      </div>
    </section>
</main>
{%endblock%}

notifications/templates/notifications/notification-list.html
{% extends 'homepage.html' %}

{% block content %}
<main class="py-5">
    <section  class="mb-5">
         <div class="container">
              <h2 class="mb-4">Your Notifications</h2>
              <table class="table table-striped">
                <thead class="thead-dark">
                  <tr>
                    <th scope="col">#</th>
                    <th scope="col">Title</th>
                    <th scope="col">Reason</th>
                    <th scope="col">Task</th>
                    <th scope="col">Type</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                {% for notification in notifications %}
                  <tr>
                    <th  scope="row">{{ notification.id }}</th>
                    <td class="text-center" scope="row">{{ notification.title }} </td>
                    <td class="text-center" scope="row">{{ notification.reason }}</td>
                    <td class="text-center" scope="row">{{ notification.reporter }}</td>
                    <td class="text-center" scope="row">{{ notification.type }}</td>
                    <td class="text-center" scope="row">
                        <a class="btn btn-success btn-sm" href="{% url 'notifications:detail' notification_id=notification.id %}">View Details</a>
                    </td>
                    <td><a class="btn btn-danger btn-sm" href="{% url 'notifications:delete' notification_id=notification.id %}">Delete</a></td>


                  </tr>
                {% endfor %}
                </tbody>
              </table>
         </div>
    </section>
</main>
{% endblock %}